### ISSUE TITLE
Hunter Loftis - We Will All Be Game Programmers

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#10]
speaker: Hunter Loftis
topic: We Will All Be Game Programmers
video: https://www.youtube.com/watch?v=avwDj3KRuLc
issue: 10

Hunter Loftis is responsible for the Node.js platform at Heroku. When he’s not working at Heroku, he runs PlayfulJS, a website of cool JavaScript code snippets.

One of the better well-known demos on PlayfulJS is a re-creation of the Doom rendering engine in JavaScript. After building this, Hunter was contacted by Warp records about building a first-person shooter in JavaScript.

One of the issues with this request was the timeframe — three weeks to build the game to coincide with an album release, and with a tiny budget. On top of that, the game had to work on desktop, Android, and iOS. So, Hunter rationalized and decided to accept the project.

After accepting the project for what he thought would be a small, indie release, Hunter realized that the artist (Rustie) was huge in the UK and overseas, and this release would be a huge deal.

[JavaScript Training from NewCircle here](http://crcl.to/72rru)

**Comment by bkil-syslogng** [comment]
+
