### ISSUE TITLE
Gergely Kmethy: Cultivating quirkiness - True leadership occurs in the kitchen!

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#104]
speaker: Gergely Kmethy
topic: Cultivating quirkiness - True leadership occurs in the kitchen!
video: http://www.ustream.tv/recorded/93005269
length: 45 min

The key to long-term business success is the elusive “competitive advantage”. Real competitive advantage is tacit knowledge that cannot be copied. Strong companies tend to have very distinct company culture: “The way we do things around here”. But how are people “indoctrinated” in company culture? The venue is the teams, and team rituals play a significant role. In his presentation Gergely explores why team rituals are essential in forming and transmitting the company DNA.

**Comment by gyp** [comment]
Ustream is gone, but the presentation is still available at https://www.youtube.com/watch?v=lTMWQsbFlLQ
