### ISSUE TITLE
Jeff Whelpley, Patrick Stapleton - Angular 2 Server Rendering

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#11]
speaker: Jeff Whelpley, Patrick Stapleton
topic: Angular 2 Server Rendering
video: https://www.youtube.com/watch?v=0wvZ7gakqV4

Jeff Whelpley, Patrick Stapleton Talk about 'Angular 2 Server Rendering' at [AngularU in San Francisco](https://AngularU.com).

Angular2 was built from the ground up to potentially run anywhere, including your web server. In this talk, we will go through the implications of this design and demonstrate the power of rendering your Angular2 app on the server.
- [Session Details](https://angularu.com/ng/session/2015sf/angular-2-server-rendering)
- [Session Photos](https://angularu.com/ng/session/2015sf/angular-2-server-rendering#photos)
- [Angular U site](https://angularu.com)

**Comment by presidento** [comment]
:+1:

**Comment by tamascsaba** [comment]
:thumbsup:
