### ISSUE TITLE
 Mob Programming, A Whole Team Approach

### ISSUE THREAD

**Issue by csernazs** [balabit/coderegation#110]
speaker: Woody Zuill
topic: Mob Programming is a development practice where the whole team works on the same thing, at the same time, in the same space, and on the same computer. 
video: https://www.youtube.com/watch?v=8cy64qkgTyI
length: 50:24

Mob Programming, A Whole Team Approach

Mob Programming is a development practice where the whole team works on the same thing, at the same time, in the same space, and on the same computer. It is a whole-team approach to doing all the work the team does including designing, coding, testing, and working with the customers, users and other stakeholders. This is an evolutionary step beyond pair programming, and accentuates face-to-face communication, team alignment, collaboration, and self-organizing team concepts of the Agile approach to software development. Mob Programming can be a highly effective approach to software development. Please join me as I share how the concept got started, the benefits, techniques we use, and some of the problems we've faced.

Woody Zuill, Woody Zuill Agile Guide

Woody Zuill, a Programmer, Senior Consultant, Trainer, and Agile Coach, has been programming computers for 30+ years. He is a pioneer of the Mob Programming approach to teamwork in software development, and is considered one of the founders of the "#NoEstimates" discussion on Twitter.

**Comment by attilammagyar** [comment]
Haven't we already watched this: #33 ?

**Comment by csernazs** [comment]
Sorry, I jumped the gun. This was presented at craft and many of us are interested in this topic.

**Comment by attilammagyar** [comment]
I just wanted to indicate that this had been already scheduled, but if there's demand, I don't see any reason not to watch it again.
