### ISSUE TITLE
Guido van Rossum - Type Hints in Python

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#12]
date: 2016-03-23
speaker: Guido van Rossum
topic: Type Hints in Python
video: https://www.youtube.com/watch?v=2wDvzy6Hgxg
issue: 12

Guido van Rossum talks about type hints in Python 3.
- [PEP 3107](https://www.python.org/dev/peps/pep-3107/)
- [PEP 0484](https://www.python.org/dev/peps/pep-0484/)

**Comment by csernazs** [comment]
+1
