### ISSUE TITLE
Mark McKergow - Leading as a host, not a hero

### ISSUE THREAD

**Issue by bkil-syslogng** [balabit/coderegation#122]
speaker: Mark McKergow
topic: Leading as a host, not a hero
video: http://www.ustream.tv/recorded/93002716
length: 47:30

How to build engagement and responsiveness using a new (yet ancient) leadership metaphor 
When we think about leading teams, it’s easy to look too hard at the leader as an individual. What matters more is the relationship between the leader and the team. Mark McKergow will speak about the new yet ancient metaphor of leading as a host, not a hero (or indeed a servant). Building on thousands of years of host-guest relationships, Mark will share his research into how great hosts can lead, and how leaders can learn to host. Thinking of the team as your guests is a rapid and effective first step towards engagement and progress.

**Comment by presidento** [comment]
The idea that the leadership is a dance of stepping forward and backward is a good idea, but the talk was a bit verbose, it could be explained in the half time.

**Comment by bkil-syslogng** [comment]
Yes, a TL;DR version would have been fine.
