### ISSUE TITLE
Breaking the x86 Instruction Set

### ISSUE THREAD

**Issue by Kokan** [balabit/coderegation#129]
speaker: Christopher Domas 
topic: Breaking the x86 Instruction Set
video: https://www.youtube.com/watch?v=KrksBdWcZgQ
length: 44:29

A processor is not a trusted black box for running code; on the contrary, modern x86 chips are packed full of secret instructions and hardware bugs. In this talk, we'll demonstrate how page fault analysis and some creative processor fuzzing can be used to exhaustively search the x86 instruction set and uncover the secrets buried in your chipset.

**Comment by bkil-syslogng** [comment]
Seen it - good material.
