### ISSUE TITLE
James Powell - Generators Will Free Your Mind

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#13]
speaker: James Powell
topic: Generators Will Free Your Mind
video: https://www.youtube.com/watch?v=RdhoN4VVqq8

What are generators and coroutines in Python? What additional conceptualisations do they offer, and how can we use them to better model problems? This is a talk I've given at PyCon Canada, PyData Boston, and PyTexas. It's an intermediate-level talk around the core concept of generators with a lot of examples of not only neat things you can do with generators but also new ways to model and conceptualise problems.

**Comment by presidento** [comment]
:+1:
