### ISSUE TITLE
A Whole New World

### ISSUE THREAD

**Issue by vlaci** [balabit/coderegation#133]
speaker: Gary Bernhardt
topic: how decades old legacy systems define our present
video: https://www.destroyallsoftware.com/talks/a-whole-new-world
length: 21:20

This talk announces the most ambitious software project I've ever undertaken, then considers why its existence is so surprising (and in some cases frustrating) to people.

**Comment by presidento** [comment]
The topic is interesting, but the audio quality is a bit poor, it is better to watch with headphones.

**Comment by attilammagyar** [comment]
We watched it and there was nothing wrong with it. Except its title. It keeps triggering that earworm song in my head. (>_<)
