### ISSUE TITLE
Kevlin Henney - Move Slow and Mend Things

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#138]
speaker: Kevlin Henney
topic: Move Slow and Mend Things
video: https://www.youtube.com/watch?v=1kklyq4XYpw
length: 48:26

Velocity. Sprints. Move fast and break things. There is a seeming obsession with speed of software development that is often at the expense of the software and its development. Velocity is a question of direction, not just magnitude. Sprints are not about sprinting; they're about sustainable pace. Time to market is less important than time in market. Full-stack development is normally a statement about technology, but it also applies to individuals and interactions. The full stack touches both the code and the world outside the code, and with that view comes responsibility and pause for thought. Doing the wrong thing smarter is not smart. The point of a team is its group intelligence not its numbers. Is scaling up the challenge, or is scaling down the real challenge? Is architecture a fixed technical plan or an unfolding hypothesis? Is code quality just something for the developers, or is it also something for the customer? Are tests extra to or a part of development? Let's slow down and learn things.

**Comment by presidento** [comment]
Good video, good talk. (But there are some already mentioned things at the end.)
