### ISSUE TITLE
Rich Hickey: Simple Made Easy

### ISSUE THREAD

**Issue by kissgyorgy** [balabit/coderegation#146]
speaker: Rich Hickey
topic: Simple Made Easy
video: https://www.infoq.com/presentations/Simple-Made-Easy
length: 1:01

Rich Hickey emphasizes simplicity’s virtues over easiness’, showing that while many choose easiness they may end up with complexity, and the better way is to choose easiness along the simplicity path.

**Comment by attilammagyar** [comment]
See also: https://8thlight.com/blog/uncle-bob/2011/10/20/Simple-Hickey.html /via @algernon
