### ISSUE TITLE
Zoltán Ormándi - TDD Anti-Patterns (HU)

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#15]
speaker: Zoltán Ormándi
topic: TDD Anti-Patterns (HU)
video: https://www.youtube.com/watch?v=Odn2Z2XAhCk

This is a Hungarian-speaking event.

Az előadásában a TDD kerül előtérbe, mely szerencsére már nem csak egy trendi újdonság, hanem kezd elfogadott standard lenni a szoftverfejlesztői szakmában Magyarországon is. Zoli az elmúlt 10-15 év tapasztalatait osztja meg velünk arról, hogyan érdemes TDD-zni, kiemelt figyelmet fordítva a módszertan elrettentően rossz alkalmazásaira.

**Comment by bazsi** [comment]
:+1:

**Comment by tamascsaba** [comment]
:thumbsup:

**Comment by attilammagyar** [comment]
watched it last week
