### ISSUE TITLE
Edward Robe - Ego Down - Eliminating pride from criticism, the Army way

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#152]
speaker: Edward Robe
topic: Ego Down - Eliminating pride from criticism, the Army way
video: http://www.ustream.tv/recorded/110522529
length: 45 min

How do you get a bunch of Type-A alpha males to make and accept constructive criticism of their ideas when lives are on the line? This is a conundrum that the U.S. military solved long ago - and the lessons learned can be applied to any sphere of business, big or small. 

The U.S. Army is not exactly known as an institution of innovation - most military organizations aren’t! Yet time and again, history has shown that the general who adapts quickly and effectively on the battlefield will consistently defeat an enemy who refuses to change their tactics and strategy. So how does one manage that level of flexibility and resourcefulness when you have such a strict hierarchy and willful personalities? Through careful processes and planning that have been perfected over the decades. In this presentation, I will discuss some of the basic strategies the U.S. military uses in their struggle to keep a notoriously bureaucratic institution as lean and adaptable as possible, and how these methods can be applied to make even the most headstrong business management team learn new techniques and methodologies in their quest for success.

**Comment by presidento** [comment]
I was there, I really liked it.

**Comment by attilammagyar** [comment]
The ustream link seems to be broken and I cannot seem to find an alternative link. :-(

**Comment by Kokan** [comment]
This link seems to work: https://www.ustream.tv/recorded/116810172

**Comment by attilammagyar** [comment]
Thank you!
