### ISSUE TITLE
Harald Massa - Becoming a better programmer

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#16]
speaker: Harald Massa
topic: Becoming a better programmer
video: http://pyvideo.org/video/1324/becoming-a-better-programmer

So you have selected the best possible programming language; you learned about object oriented design, functional paradigmas, test driven development and the Structure and interpretation of computer programs. What else can you do? Harald did research and experimented outside computer sciences. What methods and substances are available to tune your brain for programming? This talk will describe personal experiences with various motivational, self discipline, learning and information management techniques; substances and exercises to tune your brains operating system. There will be expeditions into results from brain research. A critical judgement, pointing out snake oil and stuff that worked.

**Comment by presidento** [comment]
:+1:

**Comment by csernazs** [comment]
+1

**Comment by presidento** [comment]
:-1: The quality is bad: the slides are almost unreadable, and the audio is quiet and it sounds only in the left speaker.

**Comment by presidento** [comment]
Today's video (#18) was higher quality, but it was also hard to listen to because of the poor quality of the video and audio. This one is worse, so it can be watchable at home with headphones, but it is not suitable for us in my opinion.
