### ISSUE TITLE
Péter Szabó - Method restrictions (abstract, final, @override etc.) and implementing them for Python

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#17]
speaker: Péter Szabó
topic: Method restrictions (`abstract`, `final`, `@override` etc.) and implementing them for Python
video: http://pyvideo.org/video/1314/method-restrictions-abstract-final-override-e

The earlier a bug is discovered, the cheaper it is to fix it. Method restrictions (such as abstract, final and `@Override`) help the programmer in discovering incompatibilities between a class and its subclass early (i.e. at startup time for Python and at compile time for compiled languages). Python doesn’t provide method restrictions out of the box. To implement them, we take a deep dive to the realms of Python metaprogramming (decorators, metaclasses, method wrappers, traceback inspection and builtins). Lots of short and code examples will be provided to show the building blocks and how we combine them.

**Comment by attilammagyar** [comment]
Alternate links:

https://www.youtube.com/watch?v=WX7aB0e4-Lk (the one above)
https://www.youtube.com/watch?v=OAemUvFGhE4

**Comment by presidento** [comment]
The video of Péter Szabó has a very bad audio quality, so we cannot watch it in our environment.

(@attilammagyar Your second video is a different one about Intel's Python distribution and profiler.)

**Comment by attilammagyar** [comment]
@presidento I wonder what the other link that I mixed this one up with could have been. (O_o;)
