### ISSUE TITLE
Armin Ronacher - 5 Years of Bad Ideas

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#18]
speaker: Armin Ronacher
topic: 5 Years of Bad Ideas
video: https://www.youtube.com/watch?v=8e0l_Dt28MQ

What was my motivation for working with Python after two years of PHP? There is so much you can do. Functions are objects you can pass around, you can decompile functions to see how they work internally, you can alias a bound method to a global function and it will just work. You can change import semantics, override the method resolution order, you can write metaclasses, you can hook into the CPython interpreter API and much more.

Five years later I came to the conclusion that this is really not what Python is about and that a lot of what I did was interesting but not necessarily a good idea. This talk is a 45 minute recompilation of things I really shouldn’t have done in the first place. Expect a bunch of neat and interesting hacks that showcase the possibilities of the language.

**Comment by csernazs** [comment]
+1

**Comment by bazsi** [comment]
+1

**Comment by presidento** [comment]
Planned for 4 November.
