### ISSUE TITLE
Dan McKinley - Choose Boring Technology

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#199]
speaker: Dan McKinley
topic: Choose Boring Technology
video: https://www.youtube.com/watch?v=wUmx-dlYS34
length: 31:23

Dan McKinley, an early engineer at Etsy.com and current engineer at Stripe, knows first-hand how much choosing the right technology matters for a business. As he contributed to soaring growth of his companies, he saw the consequences of bad technology choices and the joys of pragmatic ones. After nearly a decade of experience, he has figured it out. Organizations should choose boring technology.

See also: http://boringtechnology.club/

**Comment by presidento** [comment]
It sounds exciting, I have read the slides.
