### ISSUE TITLE
Martin Fowler - Microservices

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#2]
speaker: Martin Fowler
topic: Microservices
video: https://www.youtube.com/watch?v=wgdBVIX9ifA

In the last decade or so we've seen a number of new ideas added to the mix to help us effectively design our software. Patterns help us capture the solutions and rationale for using them. Refactoring allows us to alter the design of a system after the code is written. Agile methods, in particular Extreme Programming, give us a highly iterative and evolutionary approach which is particularly well suited to changing requirements and environments. Martin Fowler has been a leading voice in these techniques and will give a suite of short talks featuring various aspects about his recent thinking about how these and other developments affect our software development.

**Comment by presidento** [comment]
:+1:

**Comment by presidento** [comment]
[It was on May 12, 2015.](http://balabit.github.io/coderegation/notes/2015-05-12-Martin-Fowler-Microservices/)
