### ISSUE TITLE
Ádám Balogh - Rest Key Concepts

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#20]
speaker: Ádám Balogh
topic: Rest Key Concepts
video: https://www.youtube.com/watch?v=9gou0ta3os4
issue: 20

Hungarian-speaking video.

This presentation is about the RESTful services.

Warning: the audio quality of the first 5 minutes is bad, but after that is good enough.

**Comment by tamascsaba** [comment]
:thumbsup:

**Comment by presidento** [comment]
It is mostly for beginners. Most of the questions were about API versioning.
