### ISSUE TITLE
Jafar Husain - The Evolution of JavaScript

### ISSUE THREAD

**Issue by tamascsaba** [balabit/coderegation#23]
speaker: Jafar Husain
topic: The Evolution of JavaScript
video: https://www.youtube.com/watch?v=DqMFX91ToLw

Jafar Husain discusses interesting features that can be used today in ES6/7, such as Object.observe, async functions and async generators, while also giving a peek at what's being explored for ES7 to make async programming easier.

**Comment by tamascsaba** [comment]
Related video: https://www.youtube.com/watch?v=lil4YCCXRYc

**Comment by gyorkop** [comment]
+1

**Comment by presidento** [comment]
We've watched it last week.

**Comment by tamascsaba** [comment]
What was the conclusion?
Sometimes I would like to join via skype or hangouts :), if it possible.

**Comment by presidento** [comment]
We understand async/await more than before. (But not enough yet.) Nice concept, thanks for the video.

**Comment by attilammagyar** [comment]
Here's a different approach for telling the story of javascript: https://www.destroyallsoftware.com/talks/the-birth-and-death-of-javascript :-)

**Comment by presidento** [comment]
I have created an issue for it: #48
