### ISSUE TITLE
Pascal Precht - Dependency Injection for Future Generations - JSConf BP

### ISSUE THREAD

**Issue by tamascsaba** [balabit/coderegation#24]
speaker: Pascal Precht
topic: Dependency Injection for Future Generations
video: https://www.youtube.com/watch?v=8c-qv9TisVE

Because dependency injection is cool and that it makes life of all us developers a looot easier, we start off this talk by first understanding what dependency injection stands for and why it is such a blessing in disguise...and also because first things first. Once that is clear we can dive deeper into some existing implementations, to get a real feel of how it all works, and finish by looking at how these implementations are used inside the new Angular 2, by embracing the power of TypeScript annotations.

**Comment by presidento** [comment]
:+1:
