### ISSUE TITLE
Martin Fowler: Workflows of Refactoring

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#26]
speaker: Martin Fowler
topic: Workflows of Refactoring
video: https://www.youtube.com/watch?v=vqEg37e4Mkw

Over the last decade or so, Refactoring has become a widely used technique to keep a high internal quality for a codebase. However most teams don't make enough use of refactoring because they aren't aware of the various workflows in which you can use it. In this keynote talk from OOP 2014 in Munich, Martin Fowler explores some of these workflows: such as Litter-Pickup Refactoring, Comprehension Refactoring, and Preparatory Refactoring. Martin also reminds people why common justifications for refactoring will sabotage your best efforts. (This talk also has a treatment as an infodeck.)

[More information about Martin Fowler](www.martinfowler.com)
[More information about OOP Conference](www.oopconference.com)

**Comment by presidento** [comment]
I've seen it, it is worth to watch.

**Comment by presidento** [comment]
It is planned for 21st October.

**Comment by presidento** [comment]
It is postponed to 28 October due to a conflicting live event (#32).

**Comment by gyorkop** [comment]
+1

**Comment by attilammagyar** [comment]
Watched it yesterday
