### ISSUE TITLE
Martin Fowler: Not Just Code Monkeys

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#27]
speaker: Martin Fowler
topic: Not Just Code Monkeys
video: https://www.youtube.com/watch?v=Z8aECe4lp44

This is the second part of Martin Fowlers keynote at OOP 2014 in Munich and is a tricky talk to describe. Usually Martin likes a title and abstract to describe what the talk is about - but this talk is a journey, and he doesn't want to tell you where he's going, but instead to explore the ground with him. Martin Fowler will say that it starts with his biggest problem with most adoption of agile software development - the nature of the interaction between users, analysts, and programmers. It goes on to explore these roles, raising questions about the relationship of programmers to users, our responsibilities to them, and finally the Two Great Challenges that I think programmers need to face up to.

[More information about Martin Fowler](www.martinfowler.com)
[More information about OOP Conference](www.oopconference.com)

**Comment by presidento** [comment]
I haven't seen it, but the first part (#26) was very good.

**Comment by gyorkop** [comment]
+1

**Comment by attilammagyar** [comment]
scheduled for this week
