### ISSUE TITLE
K Lars Lohn - The Well Tempered API

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#3]
speaker: K Lars Lohn
topic: The Well Tempered API
video: https://air.mozilla.org/the-well-tempered-api-2/

Centuries ago, a revolution in music enabled compositions to still be playable hundreds of years later. With compromises in tuning, a universal musician's API became possible: the piano keyboard.

In the world of software, we have business logic, implementations, and abstractions. The more loosely we couple these, the more flexible, resilient and long lasting our software becomes. However, it's not an easy task: our tools and inclinations don't lead us the right way. Just as in music, it may take a step away from purity for software to achieve the highest level of resiliency.

This multimedia presentation uses code examples in Python from Socorro, the Mozilla Firefox Crash Reporting System. This reveals some enlightening parallels between API abstractions and centuries old music. Employing abstractions that are slightly "out of tune", Socorro scales and flexes with remarkable ease.

And, by the way, this is likely the only technical presentation you've ever encountered that features live music on an electric bassoon...

**Comment by nyirog** [comment]
+1

**Comment by bkil-syslogng** [comment]
+

**Comment by bkil-syslogng** [comment]
Please repeat this one on an occasion when I will be around, because I told Athos yesterday that I won't participate this time.

**Comment by presidento** [comment]
We will watch it today. ;)

**Comment by bkil-syslogng** [comment]
Good for you. So will Athos also come after all?

**Comment by presidento** [comment]
Okay, we postponed it.

**Comment by presidento** [comment]
Planned for next week.

**Comment by bkil-syslogng** [comment]
Athos 10 perce mondta, hogy rábeszéltétek, hogy megy ő is. Nem azt mondom,
hogy ne mozizzatok, csak valami mást rakjatok be amit a bkil nem lájkolt,
ha már mindnek 1 szavazata van. :-p

És itt dolgozok egyébként a szobában, csak mindjárt indulnom kell meetupra
a BME-re..

**Comment by presidento** [comment]
Watched last week.

**Comment by bkil-syslogng** [comment]
Unfortunately, it wasn't good enough.
