### ISSUE TITLE
Deploy Big Data services the easy way

### ISSUE THREAD

**Issue by gorosz** [balabit/coderegation#32]
Big data solutions involve many technologies working together. Whether it’s collection, analysis, or action, all of those components must be configured, their relationships defined, and deployed. In today’s dynamic data environment, the deployment is bound to change, need to be updated, or replicated. You need an infrastructure and tool set that keep your focus on the data. Flexibility in big data infrastructure automation, and examples of use cases are discussed in detail in this webinar.

This is a webinar!

Live broadcast: 21. Oct.  18:00 - 19:00 CET

Click here to attend: http://www.brighttalk.com/webcast/6793/175487

**Comment by presidento** [comment]
Thank you for the recommendation, it is planned for 21 October.

**Comment by presidento** [comment]
We tried it, but it was not worth to watch.
