### ISSUE TITLE
Woody Zuill: Mob Programming - A Whole Team Approach

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#33]
speaker: Woody Zuill
topic: Mob Programming - A Whole Team Approach
video: https://www.youtube.com/watch?v=OWcKSletcOU
length: 1 hour 2 minutes

Mob programming is a development approach in which the whole team works on the same thing at the same time, in the same space, and at the same computer. This is a whole team approach to doing all the work the team does—including coding, designing, testing, and working with the customers (stakeholders, product owners, users, and so on). This session takes a look at the practice and explores the benefits and some ideas you can try on your own team.

**Comment by bkil-syslogng** [comment]
+

**Comment by attilammagyar** [comment]
We were a little bit skeptic about this idea. Most of the benefits mentioned can be obtained by normal pair-programming as well, and the results were anecdotes rather than evidences.
