### ISSUE TITLE
Carina C. Zona: Consequences of an Insightful Algorithm

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#34]
speaker: Carina C. Zona
topic: Consequences of an Insightful Algorithm
video: https://www.youtube.com/watch?v=znwWYR1mzzw
length: 30 minutes

We have ethical responsibilities when coding. We’re able to extract remarkably precise intuitions about an individual. But do we have a right to know what they didn’t consent to share, even when they willingly shared the data that leads us there? A major retailer’s data-driven marketing accidentally revealed to a teen’s family that she was pregnant. Eek.

What are our obligations to people who did not expect themselves to be so intimately known without sharing directly? How do we mitigate against unintended outcomes? For instance, an activity tracker carelessly revealed users’ sexual activity data to search engines. A social network’s algorithm accidentally triggered painful memories for grieving families who’d recently experienced death of their child and other loved ones.

We design software for humans. Balancing human needs and business specs can be tough. It’s crucial that we learn how to build in systematic empathy.

This presentation is from JSConf EU 2015.

**Comment by bkil-syslogng** [comment]
+

**Comment by bkil-syslogng** [comment]
It was a bit too 'soft'. Neither did it contain enough constructive information.
