### ISSUE TITLE
Jacob Page - Writing elegant UI code with FRP

### ISSUE THREAD

**Issue by tamascsaba** [balabit/coderegation#35]
speaker: Jacob Page
topic: Writing elegant UI code with FRP
video: https://www.youtube.com/watch?v=jF4nXiALYtY
length: 28 minutes

Functional Reactive Programming, you can merge all the async things into one unified interface, streams of events. Then take these streams and elegantly transform and combine them with operations like map, filter, combine, merge, and throttle.

**Comment by presidento** [comment]
Watched today, I'll document it soon.

**Comment by tamascsaba** [comment]
yeeep :) :hamburger: :pizza: :beer: :baby_bottle:
