### ISSUE TITLE
Ördög Rafael - Tanuljunk meg esni 

### ISSUE THREAD

**Issue by tamascsaba** [balabit/coderegation#38]
speaker: Ördög Rafael
topic: Tanuljunk meg esni 
video: https://www.youtube.com/watch?v=tK_99x7-z6w
length: 53 min

A mikroszolgáltatás-orientált architektúra jó dolog, de megvannak a maga kihívásai. Ördög Rafael, aka DeVill "Esni is tudni kell" c. előadásában arra keresi a választ, hogyan lehet felkészülni a szolgáltatások közötti kommunikáció során fellépő problémákra. Amíg minden egy gépen fut egy processzben, addig természetesnek vesszük, hogy az összes utasítás végrehajtódik. A mikroszolgáltatásoknál viszont fel kell készülni, hogy nagyot lehet esni. DeVill arról fog mesélni, hogyan írjunk olyan robusztus kódot, ami garantálja, hogy egy-egy botlás után karcolás nélkül és azonnal tudjunk talpra állni.

**Comment by raczimre** [comment]
+1

**Comment by attilammagyar** [comment]
+1
