### ISSUE TITLE
Golden Krishna: The Best Interface is No Interface

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#42]
speaker: Golden Krishna
topic: The Best Interface is No Interface
video: https://www.youtube.com/watch?v=w0AdsVReXi8
length: 38 min

Many believe the future of design is in screens. They're wrong. Our love for the digital interface is out of control. This conversation, led by Golden Krishna, will explore a better path: NoUI. Eliminating counterintuitive input mechanisms for natural inputs inverts the contemporary focus of software design to have computers adapt for people, rather than people adapt for computers. The results can have a profound impact on your design process and our lives.

**Comment by bkil-syslogng** [comment]
+

**Comment by presidento** [comment]
planned for next week
