### ISSUE TITLE
Kevlin Henney - FizzBuzz Trek

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#43]
speaker: Kevlin Henney
topic: FizzBuzz Trek
video: https://vimeo.com/144335290
length: 51 min

FizzBuzz. It's a drinking game. It's an educational game to teach kids division. It's an interview question. It's a coding kata. It's all these things. And it can be fun. It can also be used to illustrate different coding paradigms, languages and techniques, from the serious to the jocoserious to the you-cannot-be-serious. This talk uses this simple problem to take you on a bazaar and bizarre trek, from plain examples to provocative examples in common and less common languages, sequential to concurrent, procedural to functional, elegant to ridiculous.

**Comment by presidento** [comment]
:+1: Nice talk, I suggest watching next week.

**Comment by presidento** [comment]
Watched this week, it was worth to it.
