### ISSUE TITLE
Charles Galambos - Reinforcement Learning and its use in real-time applications

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#5]
speaker: Charles Galambos
topic: Reinforcement Learning and its use in real-time applications
video: https://skillsmatter.com/skillscasts/6462-reinforcement-learning-and-its-use-in-real-time-applications#

Reinforcement Learning is a powerful technique for identifying the best actions to take to achieve a goal.

In this talk you will see some of the algorithms used to learn effective behaviours. In particular I will look at temporal differencing and how it can be used in conjunction with a recurrent neural network in a real time environment.

**Comment by bkil-syslogng** [comment]
+
