### ISSUE TITLE
Dan J. Bernstein, Tanja Lange - PQCHacks (Post-Quantum Cryptography)

### ISSUE THREAD

**Issue by mikkancso** [balabit/coderegation#50]
speaker: Daniel J. Bernstein, Tanja Lange
topic: Post-Quantum Cryptography
video: https://www.youtube.com/watch?v=6XeBvdm8vao
length: ~60 minutes

A gentle introduction to post-quantum cryptography

Last year your friend Karen joined the alternative music scene and sent you a sound track. The government is recording everything, and this year announced that alternative music is a gateway drug to terrorism (see http://www.theguardian.com/australia-news/2015/sep/25/radicalisation-kit-links-activism-and-alternative-music-scene-to-extremism). Fortunately, Karen encrypted the email.

Fast forward to 2035. Stasi 2.0 has risen to power and has decided that, to protect society, anyone who has ever been exposed to alternative music will be sent to a „better place“. They still have a copy of Karen’s ciphertext. And here’s the really bad news: They’ve just finished building a billion-qubit quantum computer.

Back in 2015, large general-purpose quantum computers haven’t been built yet, but the consensus is that they will be built, and that they will allow well-funded attackers to retroactively break practically all of today's deployed public-key cryptography. 
RSA will be dead. 
ECC will be dead. 
DSA will be dead. 
„Perfect forward secrecy“, despite its name, won’t help. 

Fortunately, there are replacement public-key cryptosystems 
that have held up very well against analysis of possible attacks, 
including future quantum attacks. 
This talk will take a hands-on look at the two examples 
with the longest track records: namely, hash-based signatures (Merkle trees) and code-based encryption (McEliece). 

The talk will be given as a joint presentation by Daniel J. Bernstein and Tanja Lange.

**Comment by attilammagyar** [comment]
Do you have alternative link for this talk? The original seems to have been removed from YouTube.

**Comment by bkil-syslogng** [comment]
https://www.youtube.com/watch?v=6O27MykWK80
http://2015.qcrypt.net/scientific-program/

**Comment by bkil-syslogng** [comment]
https://www.youtube.com/watch?v=bbkCBlWfwaQ

**Comment by attilammagyar** [comment]
According to @mikkancso, this might be the closest talk to the one that was originally linked: https://www.youtube.com/watch?v=c7OHv-L-x50
