### ISSUE TITLE
Martin Söderström - Full Stack Testing With Docker

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#52]
speaker: Martin Söderström
topic: Full Stack Testing With Docker
video: https://www.youtube.com/watch?v=eWGLumg9qsA
length: 42 min
issue: 52

One of the problems we face in automated system testing is how to setup and manage the lifecycle of the included applications. Traditional virtualisation technologies can provide solutions to these problems, but at the price of heavy resources requirements and unacceptably long startup times.

Docker on the other hand, with lower resource requirements and shorter application startup times, has seen a lot of interest lately for looking like a better fit for automated system testing. In this session, I’ll showcase some neat ways in which Docker can be used in this area and challenge the common assumption that the costs of automated system testing outweigh the benefits.

**Comment by presidento** [comment]
We watched it, but there were not many new ideas there. Having unit tests is essential. Using containers instead of virtual machines increases the speed of starting the testing environment, of course.
