### ISSUE TITLE
Bret Victor: The Future of Programming

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#53]
speaker: Bret Victor
title: The Future of Programming
video: https://www.youtube.com/watch?v=8pTEmbeENF4
length: 33 min

"The most dangerous thought you can have as a creative person is to think you know what you're doing."
Presented at Dropbox's DBX conference on July 9, 2013. [All of the slides are available at there](http://worrydream.com/dbx/)

For his recent DBX Conference talk, Victor took attendees back to the year 1973, donning the uniform of an IBM systems engineer of the times, delivering his presentation on an overhead projector. The '60s and early '70s were a fertile time for CS ideas, reminds Victor, but even more importantly, it was a time of unfettered thinking, unconstrained by programming dogma, authority, and tradition. 'The most dangerous thought that you can have as a creative person is to think that you know what you're doing,' explains Victor. 'Because once you think you know what you're doing you stop looking around for other ways of doing things and you stop being able to see other ways of doing things. You become blind.' He concludes, 'I think you have to say: "We don't know what programming is. We don't know what computing is. We don't even know what a computer is." And once you truly understand that, and once you truly believe that, then you're free, and you can think anything.'"

**Comment by bkil-syslogng** [comment]
LOL @ slides
