### ISSUE TITLE
Soós Gábor - Staying on the edge

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#54]
speaker: Soós Gábor
topic: Staying on the edge
video: https://www.youtube.com/watch?v=E0ogLwcfWts
length: 30 min

Egy greenfield project során a cutting edge technológia használata könnyű. De mi történik akkor, ha a fejlesztés több hónapig tart? Hogyan érhetjük el, hogy folyamatosan naprakész technológiákkal dolgozzunk? Soós Gábor "Sonic" beszámol a tapasztalatairól, melyeket egy full stack microservice összerakása során szerzett az Emarsysnál.

**Comment by tamascsaba** [comment]
:+1:
