### ISSUE TITLE
Alex Chrichton: The Rust Programming Language

### ISSUE THREAD

**Issue by ihrwein** [balabit/coderegation#55]
speaker: Alex Chrichton
title: The Rust Programming Language
video: https://youtu.be/d1uraoHM8Gg
length: 60 min

Rust is an exciting new programming language that combines fine-grained control over memory layout and allocation patterns with memory and thread safety. It reached 1.0 in May of 2015 (currently at 1.6 in February of 2016) and is rapidly gaining acceptance in projects including Servo (Mozilla's next generation parallel layout engine), a block store being developed by Dropbox, and numerous startups. Its features include zero-cost abstractions, move semantics, guaranteed memory safety, threads without data races, trait-based generics, pattern matching, type inference, minimal runtime, and efficient C bindings.

Alex Crichton will present an introduction to the Rust programming language, explain how it can be used to build performant, reliable systems, and answer your questions.

**Comment by bkil-syslogng** [comment]
:+1:

**Comment by MrAnno** [comment]
:+1:

**Comment by nyirog** [comment]
+1

**Comment by presidento** [comment]
:+1:

**Comment by attilammagyar** [comment]
:+1:
