### ISSUE TITLE
Webalkalmazás architektúra 2016 - kerekasztal beszélgetés

### ISSUE THREAD

**Issue by tamascsaba** [balabit/coderegation#57]
speakers: Hodicska Gergely (Ustream), Török Dániel (Prezi), Neumark Péter (Scarab), Ferenczy Péter (WhitePages), Németh Gergely (RisingStack) és Fincza András (Emarsys)
topic: Webalkalmazás architektúra 2016 - kerekasztal beszélgetés
video: https://www.youtube.com/watch?v=S_6ThOkaQN4
length: 1:30 min

Hodicska Gergely (Ustream), Török Dániel (Prezi), Neumark Péter (Scarab), Ferenczy Péter (WhitePages), Németh Gergely (RisingStack) és Fincza András (Emarsys) többek között arról beszélgetnek, hogy milyen alkalmazásokból és service-ekből állnak össze a rendszerek a cégeiknél, mik a legnagyobb kihívások architekturális szempontból, hol és hogyan üzemeltetik a rendszerüket. A Monolitok és a Service-ek viszonya is górcső alá kerül- honnan indultak és hol tart most a folyamat, mi motiválta az átalakítást. Első kézből hallhattok arról, hogy melyik megoldások váltak be és milyen nehézségekkel kellett szembenézniük.

**Comment by attilammagyar** [comment]
The audio is best suited for headphones, so we skipped this video.
