### ISSUE TITLE
Adam Tornhill: Software design, team work and other man-made disasters

### ISSUE THREAD

**Issue by bkil-syslogng** [balabit/coderegation#59]
_You can also enjoy it live today (free drinks and pizza provided):_
_2016-04-27T18:00 @ Emarsys CraftLab_
_(~Astoria - 1053 Budapest, Kossuth Lajos utca 7-9, 2. em.)_
_http://www.meetup.com/Craft-meetup/events/230140090/_

**Adam Tornhill: Software design, team work and other man-made disasters.**
http://www.adamtornhill.com/presentations/DesignTeamDisaster.htm
http://www.adamtornhill.com/presentations/SoftwareDesignTeamWorkDisasters.pdf
http://hjerpbakk.com/blog/2015/10/29/software-design-team-work-and-other-man-made-disasters
"There's more to software development than technology. More projects fail for social reasons than due to technologies or tools. To understand why, we need to dive into social psychology to uncover the intersection between technical decisions and people. In this session you'll learn to mine social information from source code repositories. You'll see how the way you chose to organise affects the code you write and how an architecture is as much a social as a technical design. As a bonus, you'll learn about social biases and how to fight them." www.adamtornhill.com

_You can update this issue after they have uploaded the video._

**Comment by attilammagyar** [comment]
I found a lot of talks from Adam Tornhill on various video sharing websites, but none of them seems to be this one. Do you have any links?

**Comment by presidento** [comment]
There is no video since more than 1 year, I'll close it.
