### ISSUE TITLE
Houssam Fakih: My team, Me and the full-time pair-programming

### ISSUE THREAD

**Issue by bkil-syslogng** [balabit/coderegation#60]
_You can also enjoy it live today (free drinks and pizza provided):_
_2016-04-27T18:00 @ Emarsys CraftLab_
_(~Astoria - 1053 Budapest, Kossuth Lajos utca 7-9, 2. em.)_
_http://www.meetup.com/Craft-meetup/events/230140090/_

**Houssam Fakih: My team, Me and the full-time pair-programming.**
https://vidoser.org/video/131660206/full-time-pair-programming-houssam-fahik/
http://www.slideshare.net/houssamfakih/fulltime-pairprogramming-48475040
"In February, I celebrated my 4th anniversary developing using full-time pair-programming. By full-time I mean that when I arrive in the morning at work I do not have my own computer. I share a computer all the day with another developer of my team. At first sight, it might look easy, amazing and a kind of luxury. Instead of having one person to develop a new functionality we have two persons that work together on it. In reality, it is a tiring but exciting work: ‘Tiring’ because you need to have more skills than solo developers. Among these skills we can mention: coordination, accuracy, stamina, flexibility, balance, etc. ‘Exciting’ because it challenges you and if it does not challenge you it does not change you. The challenge is not only technical but also human and psychological.

_You can update this issue after they have uploaded the video._

**Comment by attilammagyar** [comment]
Sorry, I meant to apply the label on another browser tab (^^;)

**Comment by attilammagyar** [comment]
I'm getting `Error 522 Ray ID: 309d58a43ca459cc • 2016-11-30 09:42:24 UTC / Connection timed out` errors when I try to access the video, so it's not going to be this week either. :-(

**Comment by presidento** [comment]
The video link still does not work. I will close it after a year...

**Comment by presidento** [comment]
The video site is still not available. :disappointed:
