### ISSUE TITLE
Greg Young - Stop Over-Engenering

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#68]
speaker: Greg Young
title: Stop Over-Engenering
video: https://www.youtube.com/watch?v=GRr4xeMn1uU
length: 47 min

Gregory Young coined the term “CQRS” (Command Query Responsibility Segregation) and it was instantly picked up by the community who have elaborated upon it ever since. Greg is an independent consultant and serial entrepreneur. He has 15+ years of varied experience in computer science from embedded operating systems to business systems and he brings a pragmatic and often times unusual viewpoint to discussions. He’s a frequent contributor to InfoQ, speaker/trainer at Skills Matter and also a well-known speaker at international conferences. Greg also writes about CQRS, DDD and other hot topics on [codebetter.com](codebetter.com).

**Comment by bkil-syslogng** [comment]
:+1: 

https://www.infoq.com/news/2016/06/over-engineering-customer-needs

> After working with many different teams, Greg Young has found that they often are drastically over-engineering in their projects. Teams start to work on 9 month projects, but by thinking on the problem from another perspective they may be able to deliver 95% of the value in just a few weeks, Young claimed in his keynote at the recent DDD eXchange conference in London.
> 
> The reason for this over-engineering is that we are building the wrong thing. 
> [...]

**Comment by attilammagyar** [comment]
Sounds interesting, +1!

**Comment by presidento** [comment]
Please, use the _Add your reaction_ button:

![image](https://cloud.githubusercontent.com/assets/282320/19233981/3bb3aee8-8ee9-11e6-9b39-341e03516818.png)

This is the best way to vote on an issue. (The issues can be ordered based on those reactions, but not on the _content_ of the comments). Thank you!

**Comment by attilammagyar** [comment]
I had no idea that that button existed, thanks!
