### ISSUE TITLE
Rachel Davies - Coaching teams through Change

### ISSUE THREAD

**Issue by bkil-syslogng** [balabit/coderegation#79]
speaker: Rachel Davies
topic: Coaching teams through Change
video: http://www.ustream.tv/recorded/46635086
length:

When you come to a conference like this, you pick up new ideas that you’d like to try when you get back to work. However, you may feel like you hit a brick wall when it comes persuading your team to try the idea out. Resistance is very common in organisations large and small. As an agile coach, Rachel has learned that forcing adoption of new practice results in minimal compliance. Teams who don’t want to try the new approach often fall back to old ways of doing things. Come to this talk to hear some ideas about how to dissolve barriers to adopting new working practices and get your team moving in the right direction. Rachel Davies is co-author of the first “Agile Coaching” book and works in UK as Agile Coach at Unruly Media, the leading global platform for social video marketing. Internationally recognized and presenting at industry conferences worldwide, Rachel started out working as a software developer and has been an agile practitioner since 2000 applying a range of agile methods including XP, SCRUM, Lean/Kanban, and DSDM. Follow her @rachelcdavies

**Comment by presidento** [comment]
There were not much new information in this presentation, but the basics were good.
