### ISSUE TITLE
Patches carved into stone tablets…

### ISSUE THREAD

**Issue by nyirog** [balabit/coderegation#84]
speaker: Greg KH
topic: Patch hadnling, review tools
video: https://www.youtube.com/watch?v=L8OOzaqS37s
length: 44:34

Patches carved into stone tablets, why the Linux kernel developers rely on plain text email instead of using “modern” development tools.

With the wide variety of more “modern” development tools such as github, gerrit, and other methods of software development, why is the Linuxkernel team still stuck in the 1990’s with ancient requirements of plain text email in order to get patches accepted? This talk will discuss just how the kernel development process works, why we rely on these “ancient” tools, and how they still work so much better than anything else.

**Comment by bazsi** [comment]
:+1:


-- 
Bazsi
