### ISSUE TITLE
Kevlin Henney - The Error of Our Ways

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#87]
speaker: Kevlin Henney
topic: The Error of Our Ways
video: https://www.youtube.com/watch?v=IiGXq3yY70o
length: 50 min

What happens when things break? What happens when software fails? We regard it as a normal and personal inconvenience when apps crash or servers become unavailable, but what are the implications beyond the individual user? Is software reliability simply a business decision or does it have economic, social and cultural consequences? What are the moral and practical implications for software developers? And when we talk of 'systems', are we part of the 'system'? What about the bugs on our side of the keyboard? In this talk we will explore examples of failures in software and its application, and how they affect us at different scales, from user to society.

**Comment by attilammagyar** [comment]
no attendees :-(

**Comment by presidento** [comment]
Let's try it again, I want to watch it, but I had a conflicting meeting last week.

**Comment by attilammagyar** [comment]
Your wish is my command. :-)

**Comment by presidento** [comment]
It was an awesome talk.
