### ISSUE TITLE
Houssam Fakih: Never Develop Alone always with a partner

### ISSUE THREAD

**Issue by bkil-syslogng** [balabit/coderegation#92]
speaker: Houssam Fakih
topic: Never Develop Alone always with a partner
video: https://www.youtube.com/watch?v=q5t6lnCuPKQ
length: 37min
slides: http://www.slideshare.net/houssamfakih/never-develop-alone-always-with-a-partner
PDF: http://www.talkfields.com/wp-content/uploads/2016/11/Agile-Tour-London-16-Never-Develop-Alone-Always-With-a-partner-1.pdf

> The talk covers a similar topic as #60 "My team, Me and the full-time pair-programming". The first paragraph of the abstract is also the same. You can compare the slides if you want to know more about the difference.

_In February 2016, I celebrated my 4th anniversary developing using full-time pair-programming. By full-time I mean that when I arrive in the morning at work I do not have my own computer. I share a computer all the day with another developer of my team. At first sight, it might look easy, amazing and a kind of luxury. Instead of having one person to develop a new functionality we have two persons that work together on it. In reality, it is a tiring but exciting work: ‘Tiring’ because you need to have more skills than solo developers. ‘Exciting’ because it challenges you and if it does not challenge you it does not change you._

In this talk, I’ll focus on the challenges and the main benefits of this kind of pair-programming for you, for your team and for your company: How you can make the most of this kind of programming? How each pair can boost his partner? How you can improve your technique of pairing? How you can anticipate problems and fix them? What are the common errors about pairing?

**Comment by bkil-syslogng** [comment]
@presidento You may like this one as well if you were interested in #60.

**Comment by presidento** [comment]
The audio quality is poor, we cannot watch it in group. (Only individually with headset.)
